### ISSUE TITLE
If you try to add a css or js file to this sample

### ISSUE THREAD

**Issue by alberttwong** [GoogleCloudPlatform/appengine-try-php#10]
The webapp won't load it (per Chrome Developer Tool).  Is there a trick to get appengine to serve css and js files?

**Comment by alberttwong** [comment]
I updated the example in the docs to:

```
runtime: php55
api_version: 1

handlers:
# Serve images, css and js as static resources.
- url: /(.+\.(gif|png|css|js|jpg))$
  static_files: \1
  upload: .+\.(gif|png|css|js|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

#entry point file.
- url: /
  script: demo.html
```
